package com.android.sample.ui.calendar.components

// This code has been generated by an AI

import androidx.compose.foundation.layout.Arrangement
import androidx.compose.foundation.layout.Box
import androidx.compose.foundation.layout.Column
import androidx.compose.foundation.layout.PaddingValues
import androidx.compose.foundation.layout.Row
import androidx.compose.foundation.layout.Spacer
import androidx.compose.foundation.layout.fillMaxWidth
import androidx.compose.foundation.layout.height
import androidx.compose.material3.MaterialTheme
import androidx.compose.material3.Text
import androidx.compose.material3.TextButton
import androidx.compose.runtime.Composable
import androidx.compose.ui.Modifier
import androidx.compose.ui.draw.drawWithContent
import androidx.compose.ui.geometry.Offset
import androidx.compose.ui.geometry.Size
import androidx.compose.ui.graphics.BlendMode
import androidx.compose.ui.graphics.Brush
import androidx.compose.ui.graphics.Color
import androidx.compose.ui.graphics.CompositingStrategy
import androidx.compose.ui.graphics.graphicsLayer
import androidx.compose.ui.layout.onSizeChanged
import androidx.compose.ui.platform.LocalDensity
import androidx.compose.ui.platform.testTag
import androidx.compose.ui.text.TextStyle
import androidx.compose.ui.text.style.TextOverflow
import androidx.compose.ui.unit.TextUnit
import androidx.compose.ui.unit.dp
import androidx.compose.ui.unit.isUnspecified
import com.android.sample.ui.calendar.style.EventSummaryTextConfig
import com.android.sample.ui.theme.SpacingSmall

/**
 * Aggregates localized labels used by the expand/collapse toggle (like "Show more" / "Show less).
 */
data class ToggleLabels(val expand: String, val collapse: String)

/** Reusable expandable text with an optional last-line end fade and a trailing toggle button. */
@Composable
fun ExpandableText(
    modifier: Modifier = Modifier,
    text: String = "No text provided...",
    style: TextStyle = MaterialTheme.typography.titleMedium,
    collapsedMaxLines: Int = EventSummaryTextConfig().descriptionCollapsedMaxLines,
    isExpanded: Boolean = false,
    onToggleExpand: () -> Unit = {},
    onOverflowChange: (Boolean) -> Unit = {},
    showToggle: Boolean = true,
    toggleLabels: ToggleLabels = EventSummaryTextConfig().toggleLabels,
    toggleTypography: TextStyle = MaterialTheme.typography.labelMedium,
    onTextHeightChange: (Int) -> Unit = {},
    toggleTestTag: String? = null
) {
  Column(modifier = modifier.fillMaxWidth()) {
    val density = LocalDensity.current
    val fontSizePx = with(density) { style.fontSize.toPx() }
    val computedLineHeight = computeLineHeight(style)
    val lineHeightPx = with(density) { computedLineHeight.toPx() }
    val fadeWidthPx = fontSizePx * 12f

    Box(modifier = Modifier.fillMaxWidth()) {
      Text(
          text = text,
          style = style,
          maxLines = if (isExpanded) Int.MAX_VALUE else collapsedMaxLines,
          overflow = TextOverflow.Clip,
          softWrap = isExpanded || collapsedMaxLines > 1,
          onTextLayout = { result ->
            // When expanded, keep the toggle visible as "Show less"
            onOverflowChange(result.hasVisualOverflow || isExpanded)
          },
          color = MaterialTheme.colorScheme.onSurface,
          modifier =
              Modifier.onSizeChanged { onTextHeightChange(it.height) }
                  .then(
                      fadeModifier(
                          isExpanded = isExpanded,
                          showToggle = showToggle,
                          fadeWidthPx = fadeWidthPx,
                          lineHeightPx = lineHeightPx)))
    }

    ToggleSection(
        showToggle = showToggle,
        isExpanded = isExpanded,
        onToggleExpand = onToggleExpand,
        toggleLabels = toggleLabels,
        toggleTypography = toggleTypography,
        toggleTestTag = toggleTestTag)
  }
}

private fun computeLineHeight(style: TextStyle): TextUnit {
  return if (style.lineHeight.isUnspecified) {
    style.fontSize * 1.2f
  } else {
    style.lineHeight
  }
}

private fun fadeModifier(
    isExpanded: Boolean,
    showToggle: Boolean,
    fadeWidthPx: Float,
    lineHeightPx: Float
): Modifier {
  if (isExpanded || !showToggle) return Modifier

  return Modifier.graphicsLayer(compositingStrategy = CompositingStrategy.Offscreen)
      .drawWithContent {
        drawContent()
        val endX = size.width
        val startX = (endX - fadeWidthPx).coerceAtLeast(0f)
        val topY = (size.height - lineHeightPx).coerceAtLeast(0f)
        val width = (endX - startX).coerceAtLeast(0f)
        if (width > 0f && lineHeightPx > 0f) {
          drawRect(
              brush =
                  Brush.horizontalGradient(
                      colors = listOf(Color.Black, Color.Transparent),
                      startX = startX,
                      endX = endX),
              topLeft = Offset(startX, topY),
              size = Size(width, lineHeightPx),
              blendMode = BlendMode.DstIn)
        }
      }
}

@Composable
private fun ToggleSection(
    showToggle: Boolean,
    isExpanded: Boolean,
    onToggleExpand: () -> Unit,
    toggleLabels: ToggleLabels,
    toggleTypography: TextStyle,
    toggleTestTag: String?
) {
  if (showToggle) {
    Row(modifier = Modifier.fillMaxWidth(), horizontalArrangement = Arrangement.End) {
      TextButton(
          onClick = onToggleExpand,
          contentPadding = PaddingValues(0.dp),
          modifier = if (toggleTestTag != null) Modifier.testTag(toggleTestTag) else Modifier) {
            Text(
                text = if (isExpanded) toggleLabels.collapse else toggleLabels.expand,
                style = toggleTypography,
                color = MaterialTheme.colorScheme.primary)
          }
    }
  } else {
    // Keep vertical rhythm when no toggle is shown
    Spacer(Modifier.height(SpacingSmall))
  }
}
