package com.android.sample.ui.hourRecap

import android.widget.Toast
import androidx.compose.foundation.background
import androidx.compose.foundation.layout.*
import androidx.compose.foundation.layout.ExperimentalLayoutApi
import androidx.compose.foundation.layout.IntrinsicSize
import androidx.compose.foundation.lazy.LazyColumn
import androidx.compose.foundation.lazy.items
import androidx.compose.foundation.rememberScrollState
import androidx.compose.foundation.verticalScroll
import androidx.compose.material.icons.Icons
import androidx.compose.material.icons.filled.FileDownload
import androidx.compose.material.icons.filled.Info
import androidx.compose.material3.*
import androidx.compose.runtime.*
import androidx.compose.ui.Alignment
import androidx.compose.ui.Modifier
import androidx.compose.ui.draw.clip
import androidx.compose.ui.graphics.Color
import androidx.compose.ui.graphics.compositeOver
import androidx.compose.ui.platform.LocalContext
import androidx.compose.ui.platform.testTag
import androidx.compose.ui.res.stringResource
import androidx.compose.ui.text.font.FontWeight
import androidx.compose.ui.text.style.TextAlign
import androidx.compose.ui.unit.dp
import androidx.lifecycle.viewmodel.compose.viewModel
import com.android.sample.R
import com.android.sample.ui.calendar.components.DatePickerFieldToModal
import com.android.sample.ui.calendar.utils.formatDecimalHoursToTime
import com.android.sample.ui.common.Loading
import com.android.sample.ui.common.PrimaryButton
import com.android.sample.ui.common.SecondaryPageTopBar
import com.android.sample.ui.theme.ElevationLow
import com.android.sample.ui.theme.PaddingExtraSmall
import com.android.sample.ui.theme.PaddingMedium
import com.android.sample.ui.theme.PaddingSmall
import com.android.sample.ui.theme.SpacingLarge
import com.android.sample.ui.theme.SpacingMedium
import com.android.sample.ui.theme.Weight
import java.time.LocalDate
import java.time.ZoneId
import java.time.ZoneOffset
import java.time.format.DateTimeFormatter

// Modularization assisted by AI

/** Test tags for HourRecapScreen UI tests. */
object HourRecapTestTags {
  const val BACK_BUTTON = "hour_recap_back_button"
  const val SCREEN_ROOT = "hour_recap_screen_root"
  const val TOP_BAR = "hour_recap_top_bar"
  const val START_DATE = "hour_recap_start_date"
  const val END_DATE = "hour_recap_end_date"
  const val GENERATE_BUTTON = "hour_recap_generate_button"
  const val RECAP_LIST = "hour_recap_list"
  const val RECAP_ITEM = "hour_recap_item"
  const val RECAP_SHEET = "hour_recap_sheet"
  const val EXPORT_BUTTON = "hour_recap_export_button"
}

/**
 * HourRecapScreen
 *
 * A screen allowing an administrator to select a start and end date and visualize the total working
 * hours of all employees over the selected period.
 *
 * This screen currently uses fake recap data; the real implementation will later delegate the
 * date-range selection and recap generation to a dedicated ViewModel.
 *
 * UI structure:
 * - A top bar with a back button and an "Export to Excel" action button.
 * - Two date picker fields (start / end).
 * - A "Generate recap" button (enabled only when both dates are selected).
 * - A scrollable list summarizing each employee's worked hours.
 *
 * Test tags are provided through [HourRecapTestTags] to support UI testing.
 *
 * @param hourRecapViewModel ViewModel for hour recap.
 * @param onBackClick Callback invoked when the user presses the back navigation button.
 */
@OptIn(ExperimentalMaterial3Api::class)
@Composable
fun HourRecapScreen(
    hourRecapViewModel: HourRecapViewModel = viewModel(factory = HourRecapViewModel.Factory),
    onBackClick: () -> Unit = {}
) {
  val uiState by hourRecapViewModel.uiState.collectAsState()
  val context = LocalContext.current

  LaunchedEffect(uiState.errorMsg) {
    uiState.errorMsg?.let { message ->
      Toast.makeText(context, message, Toast.LENGTH_SHORT).show()
      hourRecapViewModel.clearErrorMsg()
    }
  }

  var startDate by remember { mutableStateOf<LocalDate?>(null) }
  var endDate by remember { mutableStateOf<LocalDate?>(null) }
  var selectedUser by remember { mutableStateOf<HourRecapUserRecap?>(null) }
  val bottomSheetState = rememberModalBottomSheetState(skipPartiallyExpanded = true)
  var hasGenerated by remember { mutableStateOf(false) }

  Scaffold(
      topBar = {
        SecondaryPageTopBar(
            modifier = Modifier.testTag(HourRecapTestTags.TOP_BAR),
            title = stringResource(R.string.hour_recap),
            canGoBack = true,
            onClick = onBackClick,
            backButtonTestTags = HourRecapTestTags.BACK_BUTTON,
            actions = {
              IconButton(
                  onClick = { /* Later: Export */},
                  modifier = Modifier.testTag(HourRecapTestTags.EXPORT_BUTTON)) {
                    Icon(
                        imageVector = Icons.Default.FileDownload,
                        contentDescription = stringResource(R.string.export_excel))
                  }
            })
      }) { padding ->
        Column(
            modifier =
                Modifier.padding(padding)
                    .padding(SpacingLarge)
                    .fillMaxSize()
                    .testTag(HourRecapTestTags.SCREEN_ROOT),
            verticalArrangement = Arrangement.Top) {

              // ---- Start date Picker ----
              DatePickerFieldToModal(
                  label = stringResource(R.string.startDatePickerLabel),
                  modifier = Modifier.fillMaxWidth().testTag(HourRecapTestTags.START_DATE),
                  onDateSelected = { startDate = it })

              Spacer(Modifier.height(SpacingMedium))

              // ---- End date Picker ----
              DatePickerFieldToModal(
                  label = stringResource(R.string.endDatePickerLabel),
                  modifier = Modifier.fillMaxWidth().testTag(HourRecapTestTags.END_DATE),
                  onDateSelected = { endDate = it })

              Spacer(Modifier.height(SpacingMedium))

              // ---- Generate Recap Button ----
              PrimaryButton(
                  modifier = Modifier.fillMaxWidth().testTag(HourRecapTestTags.GENERATE_BUTTON),
                  text = stringResource(R.string.hour_recap_generate),
                  enabled = startDate != null && endDate != null && !startDate!!.isAfter(endDate!!),
                  onClick = {
                    hasGenerated = true
                    hourRecapViewModel.calculateWorkedHours(
                        start = startDate!!.atStartOfDay().toInstant(ZoneOffset.UTC),
                        end = endDate!!.atTime(23, 59).toInstant(ZoneOffset.UTC))
                  })

              Spacer(Modifier.height(SpacingLarge))

              // ---- Title ----
              Text(
                  text = stringResource(R.string.hour_recap_results_title),
                  style = MaterialTheme.typography.titleMedium.copy(fontWeight = FontWeight.Bold))

              Spacer(Modifier.height(SpacingMedium))

              // ---- LOADING ----
              if (uiState.isLoading) {
                Loading(
                    modifier = Modifier.fillMaxSize(),
                    label = stringResource(R.string.loading_hours))
              } else {
                // ---- LIST OF WORKED HOURS ----
                LazyColumn(modifier = Modifier.testTag(HourRecapTestTags.RECAP_LIST)) {
                  if (uiState.userRecaps.isEmpty() && hasGenerated) {
                    item {
                      ElevatedCard(
                          modifier =
                              Modifier.fillMaxWidth()
                                  .padding(vertical = SpacingMedium),
                          colors =
                              CardDefaults.elevatedCardColors(
                                  containerColor =
                                      MaterialTheme.colorScheme.surfaceVariant.copy(alpha = 0.6f))) {
                            Column(
                                modifier =
                                    Modifier.fillMaxWidth()
                                        .padding(horizontal = SpacingLarge, vertical = SpacingMedium),
                                horizontalAlignment = Alignment.CenterHorizontally) {
                                  Icon(
                                      imageVector = Icons.Default.Info,
                                      contentDescription = null,
                                      tint = MaterialTheme.colorScheme.primary)
                                  Spacer(Modifier.height(PaddingSmall))
                                  Text(
                                      text =
                                          stringResource(
                                              R.string.hour_recap_no_events_in_range_heading),
                                      style =
                                          MaterialTheme.typography.titleSmall.copy(
                                              fontWeight = FontWeight.SemiBold))
                                  Spacer(Modifier.height(PaddingExtraSmall))
                                  Text(
                                      text =
                                          stringResource(
                                              R.string.hour_recap_no_events_in_range_details),
                                      style = MaterialTheme.typography.bodyMedium,
                                      color = MaterialTheme.colorScheme.onSurfaceVariant,
                                      textAlign = TextAlign.Center)
                                }
                              }
                    }
                  }

                  items(uiState.userRecaps, key = { it.userId }) { recap ->
                    Card(
                        modifier =
                            Modifier.fillMaxWidth()
                                .padding(vertical = PaddingSmall)
                                .testTag(HourRecapTestTags.RECAP_ITEM),
                        onClick = { selectedUser = recap },
                        elevation = CardDefaults.cardElevation(ElevationLow)) {
                          Column(modifier = Modifier.fillMaxWidth().padding(PaddingMedium)) {
                            Row(
                                modifier = Modifier.fillMaxWidth(),
                                horizontalArrangement = Arrangement.SpaceBetween,
                                verticalAlignment = Alignment.CenterVertically) {
                                  Text(
                                      text = recap.displayName,
                                      style = MaterialTheme.typography.bodyLarge,
                                      modifier = Modifier.weight(Weight))
                                  Surface(
                                      shape = MaterialTheme.shapes.small,
                                      color =
                                          MaterialTheme.colorScheme.surfaceVariant
                                              .copy(alpha = 0.6f)
                                              .compositeOver(
                                                  MaterialTheme.colorScheme.surface)) {
                                    Text(
                                        modifier = Modifier.padding(horizontal = PaddingSmall),
                                        text = formatDecimalHoursToTime(recap.totalHours),
                                        style =
                                            MaterialTheme.typography.labelMedium.copy(
                                                fontWeight = FontWeight.SemiBold))
                                  }
                                }

                            Spacer(Modifier.height(PaddingSmall))

                            Row(
                                modifier = Modifier.fillMaxWidth(),
                                horizontalArrangement = Arrangement.spacedBy(PaddingSmall)) {
                                  HourRecapStat(
                                      label =
                                          stringResource(
                                              R.string.hour_recap_completed_hours_label),
                                      value = formatDecimalHoursToTime(recap.completedHours),
                                      containerColor =
                                          MaterialTheme.colorScheme.primaryContainer,
                                      contentColor =
                                          MaterialTheme.colorScheme.onPrimaryContainer,
                                  )

                                  HourRecapStat(
                                      label =
                                          stringResource(
                                              R.string.hour_recap_planned_hours_label),
                                      value = formatDecimalHoursToTime(recap.plannedHours),
                                      containerColor =
                                          MaterialTheme.colorScheme.tertiaryContainer,
                                      contentColor =
                                          MaterialTheme.colorScheme.onTertiaryContainer,
                                  )
                                }

                          }
                        }
                  }
                }
              }
            }
      }

  if (selectedUser != null) {
    ModalBottomSheet(
        modifier = Modifier.testTag(HourRecapTestTags.RECAP_SHEET),
        onDismissRequest = { selectedUser = null },
        sheetState = bottomSheetState) {
          HourRecapUserEventsSheet(recap = selectedUser!!, onDismiss = { selectedUser = null })
        }
  }
}

@Composable
private fun HourRecapUserEventsSheet(recap: HourRecapUserRecap, onDismiss: () -> Unit) {
  val dateFormatter = remember { DateTimeFormatter.ofPattern("MMM dd, yyyy") }
  val timeFormatter = remember { DateTimeFormatter.ofPattern("HH:mm") }

  Column(
      modifier =
          Modifier.fillMaxWidth()
              .verticalScroll(rememberScrollState())
              .padding(horizontal = SpacingLarge, vertical = SpacingMedium)) {
        Row(modifier = Modifier.fillMaxWidth(), horizontalArrangement = Arrangement.SpaceBetween) {
          Text(
              text = stringResource(R.string.hour_recap_events_for_user, recap.displayName),
              style = MaterialTheme.typography.titleMedium,
              fontWeight = FontWeight.Bold,
          )
          TextButton(onClick = onDismiss) { Text(text = stringResource(R.string.close)) }
        }

        Spacer(Modifier.height(SpacingMedium))

        if (recap.events.isEmpty()) {
          Text(text = stringResource(R.string.hour_recap_no_events_for_user))
        } else {
          recap.events.forEach { event ->
            HourRecapEventCard(
                event = event, dateFormatter = dateFormatter, timeFormatter = timeFormatter)
            Spacer(Modifier.height(PaddingSmall))
          }
        }
      }
}

@Composable
@OptIn(ExperimentalLayoutApi::class)
private fun HourRecapEventCard(
    event: HourRecapEventEntry,
    dateFormatter: DateTimeFormatter,
    timeFormatter: DateTimeFormatter,
) {
  val start = event.startDate.atZone(ZoneId.systemDefault())
  val end = event.endDate.atZone(ZoneId.systemDefault())
  Card(modifier = Modifier.fillMaxWidth(), elevation = CardDefaults.cardElevation(ElevationLow)) {
    Row(modifier = Modifier.fillMaxWidth().height(IntrinsicSize.Min)) {
      Column(modifier = Modifier.weight(1f).padding(PaddingMedium)) {
        Text(
            text = event.title,
            style = MaterialTheme.typography.titleSmall,
            fontWeight = FontWeight.SemiBold)
        Spacer(Modifier.height(PaddingSmall))
        Text(
            text =
                stringResource(
                    R.string.hour_recap_event_date_time,
                    start.toLocalDate().format(dateFormatter),
                    start.toLocalTime().format(timeFormatter),
                    end.toLocalTime().format(timeFormatter)),
            style = MaterialTheme.typography.bodyMedium)
        Spacer(Modifier.height(PaddingSmall))
        FlowRow(horizontalArrangement = Arrangement.spacedBy(PaddingSmall)) {
          if (!event.isPast) {
            val timeLabel = stringResource(R.string.hour_recap_tag_future)
            val timeColor = MaterialTheme.colorScheme.tertiaryContainer // Purple for future
            RecapTag(label = timeLabel, containerColor = timeColor)
          }

          if (event.isPast) {
            val presenceLabel =
                when (event.wasPresent) {
                  true -> stringResource(R.string.hour_recap_tag_present)
                  false -> stringResource(R.string.hour_recap_tag_absent)
                  null -> stringResource(R.string.hour_recap_tag_presence_unknown)
                }
            val presenceColor =
                when (event.wasPresent) {
                  true -> Color(0xFF4CAF50) // Green for presence confirmed
                  false -> MaterialTheme.colorScheme.errorContainer // Red for absent
                  null -> MaterialTheme.colorScheme.surfaceVariant // Grey for unknown
                }
            RecapTag(label = presenceLabel, containerColor = presenceColor)
          }

          if (event.wasReplaced) {
            RecapTag(
                label = stringResource(R.string.hour_recap_tag_replaced),
                containerColor = Color(0xFFFF9800)) // Orange for replaced
          }

          if (event.tookReplacement) {
            RecapTag(
                label = stringResource(R.string.hour_recap_tag_replacement_taken),
                containerColor = Color(0xFF00BCD4)) // Cyan for took replacement
          }
        }
      }

      Box(
          modifier =
              Modifier.width(10.dp)
                  .fillMaxHeight()
                  .clip(MaterialTheme.shapes.medium)
                  .background(event.categoryColor))
    }
  }
}

@Composable
private fun HourRecapStat(
    label: String,
    value: String,
    containerColor: Color,
    contentColor: Color,
) {
  Surface(color = containerColor, contentColor = contentColor, shape = MaterialTheme.shapes.medium) {
    Column(modifier = Modifier.padding(horizontal = PaddingMedium, vertical = PaddingSmall)) {
      Text(text = label, style = MaterialTheme.typography.labelSmall, color = contentColor)
      Text(
          text = value,
          style = MaterialTheme.typography.bodyMedium.copy(fontWeight = FontWeight.Bold),
          color = contentColor)
    }
  }
}

@Composable
private fun RecapTag(label: String, containerColor: Color) {
  Surface(
      color = containerColor,
      contentColor = MaterialTheme.colorScheme.onSurface,
      shape = MaterialTheme.shapes.small) {
    Text(
        text = label,
        modifier = Modifier.padding(horizontal = PaddingSmall, vertical = PaddingExtraSmall),
        style = MaterialTheme.typography.labelMedium,
    )
  }
}
