package com.android.sample.ui.calendar

import android.widget.Toast
import androidx.compose.foundation.border
import androidx.compose.foundation.layout.fillMaxSize
import androidx.compose.foundation.layout.padding
import androidx.compose.material3.Card
import androidx.compose.material3.CardDefaults
import androidx.compose.material3.ExperimentalMaterial3Api
import androidx.compose.material3.MaterialTheme
import androidx.compose.runtime.Composable
import androidx.compose.runtime.LaunchedEffect
import androidx.compose.runtime.collectAsState
import androidx.compose.runtime.getValue
import androidx.compose.runtime.mutableStateOf
import androidx.compose.runtime.remember
import androidx.compose.runtime.setValue
import androidx.compose.ui.Modifier
import androidx.compose.ui.draw.clip
import androidx.compose.ui.platform.LocalContext
import androidx.compose.ui.platform.testTag
import androidx.compose.ui.tooling.preview.Preview
import androidx.lifecycle.viewmodel.compose.viewModel
import com.android.sample.model.calendar.Event
import com.android.sample.ui.calendar.data.LocalDateRange
import com.android.sample.ui.calendar.style.CalendarDefaults.DefaultDateRange
import com.android.sample.ui.calendar.utils.DateTimeUtils.localDateTimeToInstant
import com.android.sample.ui.theme.BorderWidthThin
import com.android.sample.ui.theme.ElevationMedium
import com.android.sample.ui.theme.PaddingSmall
import java.time.LocalTime

// Documentation generated by AI

/**
 * Test tags for identifying UI elements within the CalendarEventSelector screen. Used exclusively
 * in UI tests to locate the root composable.
 */
object CalendarEventSelectorTestTags {
  const val SCREEN_ROOT = "CalendarEventSelectorRoot"
}

/**
 * Displays an interactive weekly calendar inside a Card and allows selecting events.
 *
 * Fetches events for the visible date range, handles swipe navigation between weeks, and triggers
 * [onEventClick] when the user taps an event.
 *
 * This composable is used in screens where the user must select one or more existing events from
 * the calendar.
 */
@OptIn(ExperimentalMaterial3Api::class)
@Composable
fun CalendarEventSelector(
    calendarViewModel: CalendarViewModel = viewModel(),
    onEventClick: (Event) -> Unit = {}
) {
  // initialize the week from monday to friday
  var currentDateRange by remember { mutableStateOf(DefaultDateRange) }

  val context = LocalContext.current
  val uiState by calendarViewModel.uiState.collectAsState()
  val events = uiState.events

  // Fetch events when the screen is recomposed
  LaunchedEffect(currentDateRange) { loadEventsForDateRange(calendarViewModel, currentDateRange) }

  // Show error message if fetching events fails
  LaunchedEffect(uiState.errorMsg) {
    uiState.errorMsg?.let { message ->
      Toast.makeText(context, message, Toast.LENGTH_SHORT).show()
      calendarViewModel.clearErrorMsg()
    }
  }

  Card(elevation = CardDefaults.elevatedCardElevation(ElevationMedium)) {
    CalendarContainer(
        modifier =
            Modifier.fillMaxSize()
                .clip(MaterialTheme.shapes.medium)
                .border(
                    BorderWidthThin, MaterialTheme.colorScheme.outline, MaterialTheme.shapes.medium)
                .padding(horizontal = PaddingSmall)
                .testTag((CalendarEventSelectorTestTags.SCREEN_ROOT)),
        dateRange = currentDateRange,
        events = events,
        onSwipeLeft = {
          val nextStart = currentDateRange.start.plusWeeks(1)
          val nextEnd = currentDateRange.endInclusive.plusWeeks(1)
          currentDateRange = LocalDateRange(nextStart, nextEnd)
        },
        onSwipeRight = {
          val nextStart = currentDateRange.start.minusWeeks(1)
          val nextEnd = currentDateRange.endInclusive.minusWeeks(1)
          currentDateRange = LocalDateRange(nextStart, nextEnd)
        },
        onEventClick = onEventClick)
  }
}

/**
 * Loads the calendar events for a given date range using the provided [CalendarViewModel].
 *
 * Converts the [LocalDateRange] into corresponding [java.time.Instant] values covering the full
 * duration from start of the first day (midnight) to the end of the last day.
 */
private fun loadEventsForDateRange(
    calendarViewModel: CalendarViewModel,
    dateRange: LocalDateRange
) {
  calendarViewModel.loadEventsBetween(
      localDateTimeToInstant(dateRange.start, LocalTime.MIDNIGHT),
      localDateTimeToInstant(dateRange.endInclusive, LocalTime.MAX))
}

@Preview(showBackground = true)
@Composable
fun CalendarEventSelectorPreview() {
  CalendarEventSelector()
}
