package com.android.sample.ui.calendar

import android.widget.Toast
import androidx.compose.foundation.border
import androidx.compose.foundation.layout.fillMaxSize
import androidx.compose.foundation.layout.padding
import androidx.compose.material3.Card
import androidx.compose.material3.CardDefaults
import androidx.compose.material3.ExperimentalMaterial3Api
import androidx.compose.material3.MaterialTheme
import androidx.compose.runtime.Composable
import androidx.compose.runtime.LaunchedEffect
import androidx.compose.runtime.collectAsState
import androidx.compose.runtime.getValue
import androidx.compose.ui.Modifier
import androidx.compose.ui.draw.clip
import androidx.compose.ui.platform.LocalContext
import androidx.compose.ui.platform.testTag
import androidx.compose.ui.tooling.preview.Preview
import androidx.lifecycle.viewmodel.compose.viewModel
import com.android.sample.model.calendar.Event
import com.android.sample.ui.theme.BorderWidthThin
import com.android.sample.ui.theme.ElevationMedium
import com.android.sample.ui.theme.PaddingSmall

// Documentation generated by AI

/**
 * Test tags for identifying UI elements within the CalendarEventSelector screen. Used exclusively
 * in UI tests to locate the root composable.
 */
object CalendarEventSelectorTestTags {
  const val SCREEN_ROOT = "CalendarEventSelectorRoot"
}

/**
 * Displays an interactive weekly calendar inside a Card and allows selecting events.
 *
 * Delegates date range and swipe handling to [CalendarContainer], fetches events through the shared
 * [CalendarViewModel], and triggers [onEventClick] when the user taps an event.
 *
 * This composable is used in screens where the user must select one or more existing events from
 * the calendar.
 */
@OptIn(ExperimentalMaterial3Api::class)
@Composable
fun CalendarEventSelector(
    eventFilter: (Event) -> Boolean = { true },
    calendarViewModel: CalendarViewModel = viewModel(factory = CalendarViewModel.Factory),
    onEventClick: (Event) -> Unit = {}
) {
  val context = LocalContext.current
  val uiState by calendarViewModel.uiState.collectAsState()

  // Show error message if fetching events fails
  LaunchedEffect(uiState.errorMsg) {
    uiState.errorMsg?.let { message ->
      Toast.makeText(context, message, Toast.LENGTH_SHORT).show()
      calendarViewModel.clearErrorMsg()
    }
  }

  Card(elevation = CardDefaults.elevatedCardElevation(ElevationMedium)) {
    CalendarContainer(
        modifier =
            Modifier.fillMaxSize()
                .clip(MaterialTheme.shapes.medium)
                .border(
                    BorderWidthThin, MaterialTheme.colorScheme.outline, MaterialTheme.shapes.medium)
                .padding(horizontal = PaddingSmall)
                .testTag(CalendarEventSelectorTestTags.SCREEN_ROOT),
        calendarViewModel = calendarViewModel,
        eventFilter = eventFilter,
        onEventClick = onEventClick)
  }
}

@Preview(showBackground = true)
@Composable
fun CalendarEventSelectorPreview() {
  CalendarEventSelector()
}
